### ISSUE TITLE
Add New Products to Shopping Catalogue

### ISSUE THREAD

**Issue by agr-shrn** [DevOps-Charlie/products#5]
**As a** Merchant  
**I need** functionality to add new products to the shopping catalog with the attributes as 'Name', 'Description', 'Price'
**So that** it can be displayed on the UI and searched by the user  

**Acceptance Criteria:**
```
When I give all the attributes mentioned, I get a confirmation that the product is added.
I also get a unique Id for the product which can be used to search
```

**Comment by sonallamba** [comment]
I am adding it as a new feature too

**Comment by sonallamba** [comment]
Added to the current sprint
